name: Second app - Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_SECOND_APP_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SECOND_APP_PROJECT_ID }}

on:
  push:
    branches:
      - "master"
    paths:
      - "projects/second-app/**"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "projects/second-app"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} >> $GITHUB_OUTPUT
      - name: Promote to Production
        run: vercel promote ${{ steps.deploy.outputs }} --token=${{ secrets.VERCEL_TOKEN }}